# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa56146e33942f44a8ccbcae57e9cd53e5af9ae18718e97370da1dabe8d0734029abf7a6752d4aef03470e39d42f78bc60010e0e6cf920f15e38eb65ebbed73

test:
  secret_key_base: 2dbe53a81465199de097d7f421661f21caff0228f8ac92b2481d469eef587fb1c358326ed58a821ee069915cae7421ed3eaec25a7ecb438c93d51bf7197533f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
